### PR TITLE
Bootstrap

### PR DESCRIPTION
**Pull request by gsfr**
This moves all required bootstrapping to the app startup and makes bootstrapping users, groups, and data optional.

@kofalt Sanity check, please. Matching PR for scitran/scitran about to hit.

### CODE REVIEW

**Comment by kofalt** [comment]
Looks reasonable. I take it `create_index` is idempotent?

**Comment by gsfr** [comment]
Yup. The DB is unavailable, though, while the indexes are being built.

**Comment by kofalt** [comment]
Hmm, then I guess we'll eventually need some `await_index` equivalent for when we add new indexes. But this works for now.

**Comment by gsfr** [comment]
You can build them in the background, but that doesn't make much sense at application start, unless it really takes an inordinate amount of time.

**Comment by kofalt** [comment]
LGTM and sister PR is ready; merging.

**Pull request merged**
