### PR TITLE
Allow for custom newrelic.ini path

### PR DESCRIPTION
**Pull request by gsfr**
This consolidates all new relic code into one place and removes the hardcoded path to the ini file.

### CODE REVIEW

**Comment by kofalt** [comment]
I like that this now only tries to import when requested.

What's our plan for compatibility as infra changes?
I think merging this would further the breakage I'm experiencing in the other PR.

After that's figured out, LGTM.

**Comment by gsfr** [comment]
Are you ok with considering sci/sci aloha-only?

**Comment by kofalt** [comment]
I would like to maintain it until we have the new infra in place - among other things, the ruleset work is based off master. Without that, I don't have a coherent way to do things like cycle instance state & test the engine, etc.

Keeping sci/sci in sync seems less work than putting something else together. Alternatively, if you're comfortable with no new work progressing on master (including ruleset or engine changes) until the new infra is ready, then we can merge this.

**Comment by gsfr** [comment]
Obviously, we can't have you blocked. Can you please help me with a matching sci/sci PR?

**Comment by kofalt** [comment]
Sure, I think both PRs are pretty straightforward (this and #73).
I'll see if I can whip up compatible sci/sci PRs for each.

**Comment by kofalt** [comment]
PRs ready and master compatible; merging.

**Pull request merged**
