### PR TITLE
Zipfiles, mark 2

### PR DESCRIPTION
**Pull request by gsfr**
This upgrades our on-disk storage format for DICOMs from .tgz to .zip
@kofalt @lmperry Could you please give this a test run?
scitran/testdata already has zip files on master.
scitran/data has a matching PR and needs to be on the zip_parse branch to test this PR.

### CODE REVIEW

**Comment by gsfr** [comment]
@kofalt I just rebased this to make it mergeable again. Without breaking things, this time.

**Comment by kofalt** [comment]
Cool. I partially reviewed it this morning; testing this locally in a moment.

**Comment by kofalt** [comment]
```
Flywheel: Loading example dataset...
2015-08-20 15:21:03 initializing DB
2015-08-20 15:21:03 inspecting /home/kofalt/z/work/scitran/persistent/setup/tmp_1440102055956/144010206328443
2015-08-20 15:21:03 found 38 files to sort (ignoring symlinks and dotfiles)
2015-08-20 15:21:03 sorting     4374_1_1_dicoms.zip [818KB] (1/38)
2015-08-20 15:21:03 Parsing     4374_1_1_dicoms.zip
2015-08-20 15:21:03 Sorting     4374_1_1_dicoms.zip
Traceback (most recent call last):
  File "./bootstrap.py", line 132, in <module>
    args.func(args)
  File "./bootstrap.py", line 97, in sort
    util.commit_file(db.acquisitions, None, datainfo, filepath, args.sort_path)
  File "scitran/code/api/util.py", line 85, in commit_file
    _id = _update_db(dbc.database, datainfo)
  File "scitran/code/api/util.py", line 134, in _update_db
    project_spec = {'group': group['_id'], 'name': project_name}
TypeError: 'NoneType' object has no attribute '__getitem__'
Flywheel: Bootstrapping data failed. Cleaning up...
````

**Comment by gsfr** [comment]
Any chance this is related to not having any groups in the system due to skipping ```dbinit```?

**Comment by kofalt** [comment]
I re-ran from scratch and with some other changes and it worked :+1:

**Pull request merged**
