### PR TITLE
Add session counts to projects and collections

### PR DESCRIPTION
**Pull request by josschne**
Add a session count to the projects and collections endpoints

### CODE REVIEW

**Comment by gsfr** [comment]
Thanks, @josschne.

I'm concerned about the possible performance impact of the these additions on large databases. ```aggregate``` operations, in particular, are not cheap.

Looks like those changes are needed to close current FDM tickets, so I'm open to merging them now and revisiting later.

If counts turn out to become always-needed information, we may want to reverse the data structure in the database. Instead of having sessions point to their projects, projects will hold a list of their sessions and thus immediately know how many they contain.

**Comment by mrDarcyMurphy** [comment]
Tried this out for a separate ticket and it worked great. :+1:

**Comment by gsfr** [comment]
@josschne Feel free to merge. The only thing I would change is to use the ```ObjectId```s themselves as dictionary keys, instead of their string representations. That cuts out some clutter and seemingly useless conversions.

**Comment by josschne** [comment]
Thanks all. I'll make the suggested update and merge.

**Pull request merged**
