### PR TITLE
WIP: Fix pymongo deprecations

### PR DESCRIPTION
**Pull request by Eric89GXL**
Currently the uwsgi log is populated with a few of these warnings:
```
./persistent/logs/uwsgi.log:./util.py:140: DeprecationWarning: find_and_modify is deprecated, use find_one_and_delete, f
ind_one_and_replace, or find_one_and_update instead
```
I don't know much about `pymongo` / MongoDB -- does this seem like the right fix for those?

It seems to work okay with the sample data and have the same behavior when adding MEEG data as `master`, but it would be good if someone with more `pymongo` knowledge could confirm it's correct.

### CODE REVIEW

**Comment by kofalt** [comment]
Do you think this will satisfy #27?

Diff LGTM but I'd like @gsfr or someone to confirm sanity check.

**Comment by Eric89GXL** [comment]
Sounds like @gsfr had a local branch with similar changes a month or two ago, maybe we could use that instead of this, too.

**Comment by kofalt** [comment]
¯\_(ツ)_/¯ whatever works!

**Comment by gsfr** [comment]
This is far from complete wrt #27. I have a local stash from May(!) that I'll try to apply in the next couple of days and create a competing :smile: PR.

**Comment by kofalt** [comment]
Should we merge / close this? Is there another imminent PR that will do more than this?

**Comment by gsfr** [comment]
I'll open a more comprehensive PR as soon as #36 lands.

**Pull request closed without merging**
