### PR TITLE
Serve API with PasteScript

### PR DESCRIPTION
**Pull request by andynemzek**
Install PasteScript into your python environment and then execute a command like this:
```
/path/to/venv/bin/paster serve /path/to/api/dev.ini --reload
```
This will launch the API with PasteScript and activate automatic reloading.

### CODE REVIEW

**Comment by andynemzek** [comment]
NOTE: if we move forward with PasteScript, we should probably do some extra work to consolidate the old bin/api.wsgi with the new wsgi.py

**Comment by kofalt** [comment]
Is this a purely additive change?
Is it purely for development?
Will it influence / replace uwsgi?

**Comment by andynemzek** [comment]
Yes, yes and maybe.  This is not for prod use.  We may want to consolidate how we're launching uwsgi and paster at some point.  Otherwise, the goal would be for uwsgi to be unaffected.

**Comment by andynemzek** [comment]
Also of note here, you can use a debugger with paster.  For example, you can put this in your code:
```
import pdb; pdb.set_trace()
```
And you will be dropped into the debugger in the terminal that is running paster

**Comment by gsfr** [comment]
Very cool, @andynemzek!

@rentzso and I will exercise reloading and debugging functionality tomorrow. We'll also look into consolidating with the existing files.

**Comment by gsfr** [comment]
I'm sorry, but I have been swamped and won't get to this until next week.

**Comment by andynemzek** [comment]
Ok, just a reminder, these are purely additive changes, so they can technically be merged whenever.

**Comment by kofalt** [comment]
@josschne wanna take a look?

**Comment by gsfr** [comment]
Got `https` working with @andynemzek yesterday, simply by adding `ssl_pem` param under `[app:main]`.

**Comment by andynemzek** [comment]
Hi All, where are we at with this?  I will be needing this shortly (or something like it) to proceed with building the dev env.

**Comment by kofalt** [comment]
I've got no complaints.

**Comment by gsfr** [comment]
@andynemzek: Per our offline discussion, please rebase onto master and expand with bash wrapper. I'll help with converting the API's config system to environment variables. Will seek buy-in from @kofalt later today.

**Comment by andynemzek** [comment]
@gsfr I created a minimal bash script to run the API and mongo.  I think this script is relatively solid.  I also modified the wsgi.py file to work against the changes in master...this however, needs more work.  Again, it's additive, so we could merge and work on it incrementally if necessary.  Let me know what you think.

**Comment by gsfr** [comment]
Very cool!

I've made a few changes to the bash script, mainly created variables for 'runtime' and 'persistent' and made them optionally settable as command line arguments.

We are still missing the ability to optionally bootstrap users and/or data. I'm not sure about the exact desired behavior here, with respect to idempotence, or instance.

For reference:
```
bin/bootstrap.py users mongodb://localhost:9001/scitran bootstrap.json
bin/bootstrap.py data --copy mongodb://localhost:9001/scitran ../testdata persistent/data
```

**Comment by andynemzek** [comment]
Thanks for making those changes.  One thing to note about variable directory names...we obviously can't change the .gitignore so the dirs would appear at a `git status` as files to add to the repo.  If they indicate a directory outside the repo I guess that's fine.  

I will be checking out the bootstrapping shortly.

**Comment by andynemzek** [comment]
@gsfr see what you think about this.  Users are bootstrapped every time cause it's a fast operation.  Data is bootstrapped only if the persistent/data dir does not exist.

**Comment by andynemzek** [comment]
@gsfr can we pull this in to master?  It's needed for the dev env work.

**Comment by kofalt** [comment]
This LGTM!

It's a purely additive change, so let's just take initiative and merge this.
Open to further proposals in future PRs!

**Comment by gsfr** [comment]
Sorry for being so slow. The only thing I would have changed is the unconditional user and group bootstrapping. While user bootstrapping is pretty idempotent, group permissions simply get clobbered, which can be annoying. Also, it's not exactly fast for longer user and group lists. I'd only bootstrap if `mongo.lock` does not exist. Will follow up with another PR.

**Pull request merged**
