### PR TITLE
Sanitize filepaths

### PR DESCRIPTION
**Pull request by kofalt**
After the refactor, it looks like the API will accept any path sent to it & try to write.
`os.path.basename` is safe to call multiple times & this seemed like the best entry points.

Thoughts?

### CODE REVIEW

**Comment by rentzso** [comment]
LGTM

**Comment by josschne** [comment]
Can the filename have a trailing slash?

**Comment by kofalt** [comment]
Dunno. @rentzso?

**Comment by kofalt** [comment]
Merged for now; open to further changes regarding trailing slashes

**Comment by rentzso** [comment]
there shouldn't be any trailing slashes

**Pull request merged**
